services:
  - type: web
    name: mixx
    env: python
    buildCommand: ""
    startCommand: "python server.py"
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: MIXX_ADMIN_TOKEN
        value: Kipla@6475
      - key: MIXX_TELEGRAM_BOT_TOKEN
        value: 8876646171:AAHxcs7sKk-OHn88I1w1At1wd1ksueeekYY
      - key: MIXX_TELEGRAM_CHAT_ID
        value: "8942516822"
      - key: MIXX_TELEGRAM_BOT_USERNAME
        value: Shacklemomobot
