services:
  - type: web
    name: mixx
    env: python
    buildCommand: ""
    startCommand: "python server.py"
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: MIXX_ADMIN_TOKEN
        value: admin123
      - key: MIXX_TELEGRAM_BOT_TOKEN
        value: 8515691191:AAGr3bH187einhAvG7Jccu3ZbjsaovR8f_c
      - key: MIXX_TELEGRAM_CHAT_ID
        value: "8942516822"
      - key: MIXX_TELEGRAM_BOT_USERNAME
        value: ShackleMtnbot
